


all:
	make --no-print-directory -f ovl_proposition
	make --no-print-directory -f ovl_time
	make --no-print-directory -f ovl_always
	

clean:
	  rm -fr a.out *.log *.vcd tee

help:
	make --no-print-directory -f ovl_always help
	make --no-print-directory -f ovl_proposition help
	make --no-print-directory -f ovl_time help
